plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@aws-amplify/ui-react@*":
    dependencies:
      "@aws-amplify/core": "*"
  "@aws-amplify/ui-components@*":
    peerDependencies:
      "@aws-amplify/core": "*"
    dependencies:
      "@aws-amplify/storage": "*"
      "@aws-amplify/interactions": "*"
  "@aws-amplify/datastore@*":
    peerDependencies:
      "@aws-amplify/cache": "*"
    dependencies:
      "crypto-js": "*"
      "@aws-amplify/api-graphql": "*"
  "@aws-amplify/storage@*":
    dependencies:
      "@aws-sdk/protocol-http": "*"
      "@aws-sdk/fetch-http-handler": "*"
      "@aws-sdk/querystring-builder": "*"
  "@aws-amplify/api@*":
    dependencies:
      "@aws-amplify/auth": "*"
    peerDependencies:
      "@aws-amplify/core": "*"
      "@aws-amplify/cache": "*"
  "@aws-crypto/sha256-browser@*":
    dependencies:
      "@aws-sdk/util-utf8-browser": "*"
  "react-map-gl@*":
    peerDependencies:
      "react-dom": "*"
  "maplibre-gl-js-amplify@*":
    dependencies:
      "@aws-amplify/geo": "*"
  "@xstate/react@*":
    dependencies:
      "xstate": "*"
  "@aws-sdk/util-user-agent-node@*":
    dependencies:
      "aws-crt": "*"
  "apollo-utilities@*":
    dependencies:
      "graphql": "*"
  "apollo-codegen-core@*":
    dependencies:
      "graphql": "*"
  "apollo-codegen-swift@*":
    dependencies:
      "graphql": "*"
  "apollo-codegen-flow@*":
    dependencies:
      "graphql": "*"
  "apollo-codegen-typescript@*":
    dependencies:
      "graphql": "*"
  "apollo-codegen-scala@*":
    dependencies:
      "graphql": "*"
