name: Build and Test on Pull Request
on:
  pull_request:
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn workspace @rv-app/frontend build

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn

      # Test that the server returns an expected message
      - run: yarn workspace @rv-app/server start &
      - run: sleep 5
      - run: |
          readonly response=$(curl http://localhost:3000/)
          readonly expected="Hello, World! 4"
          if [ "$response" = "$expected" ]; then
              echo "Server queried successfully"
          else
              echo "Did not find $expected. Instead, found $response"
              exit 1
          fi
  build-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn tsc --build

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
